title: Courtney Daniels. Writer, Editor.
description: > # this means to ignore newlines until "baseurl:"
  This is my portfolio to showcase my writing and editing skills. I have 10+ years' experience writing and editing highly scientific and technical content for NASA, NOAA, the Department of Transportation, and others.
permalink: ':title/'
baseurl: "/web-portfolio" # the subpath of your site, e.g. /blog
url: "https://cdjdaniels.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Courtney Daniels # add your name
author-img: ./assets/img/IMG_6374.jpeg
about-author: I am a writer and editor open to full time and freelance work. # add description

social-github: cdjdaniels # add your Github handle
social-linkedin: www.linkedin.com/in/courtney-daniels-edits # add your Linkedin handle
social-email:cdjdaniels@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
